# coding: utf-8

"""
    Jarvice API

    The JARVICE API allows full control on running jobs as well as managing applications via PushToCompute™.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@nimbix.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openapi_client
from openapi_client.models.sched_job_status_entry import SchedJobStatusEntry  # noqa: E501
from openapi_client.rest import ApiException

class TestSchedJobStatusEntry(unittest.TestCase):
    """SchedJobStatusEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SchedJobStatusEntry
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SchedJobStatusEntry`
        """
        model = openapi_client.models.sched_job_status_entry.SchedJobStatusEntry()  # noqa: E501
        if include_optional :
            return SchedJobStatusEntry(
                job_application = '', 
                job_command = '', 
                job_end_time = 56, 
                job_name = '', 
                job_project = '', 
                job_start_time = 56, 
                job_status = '', 
                job_submit_time = 56, 
                job_substatus = 56, 
                job_walltime = ''
            )
        else :
            return SchedJobStatusEntry(
        )
        """

    def testSchedJobStatusEntry(self):
        """Test SchedJobStatusEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
