# coding: utf-8

"""
    Jarvice API

    The JARVICE API allows full control on running jobs as well as managing applications via PushToCompute™.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@nimbix.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import jarviceapi_client
from jarviceapi_client.models.vault import Vault  # noqa: E501
from jarviceapi_client.rest import ApiException

class TestVault(unittest.TestCase):
    """Vault unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Vault
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Vault`
        """
        model = jarviceapi_client.models.vault.Vault()  # noqa: E501
        if include_optional :
            return Vault(
                bucket = '', 
                confirm = '', 
                domain = '', 
                force = True, 
                name = '', 
                objects = [
                    ''
                    ], 
                password = '', 
                readonly = True
            )
        else :
            return Vault(
        )
        """

    def testVault(self):
        """Test Vault"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
