# coding: utf-8

"""
    Jarvice API

    The JARVICE API allows full control on running jobs as well as managing applications via PushToCompute™.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@nimbix.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import openapi_client
from openapi_client.api.job_control_api import JobControlApi  # noqa: E501
from openapi_client.rest import ApiException


class TestJobControlApi(unittest.TestCase):
    """JobControlApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.job_control_api.JobControlApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_action_get(self):
        """Test case for action_get

        Perform a configured action on your job  # noqa: E501
        """
        pass

    def test_batch_post(self):
        """Test case for batch_post

        Submits a job for processing.  # noqa: E501
        """
        pass

    def test_shutdown_get(self):
        """Test case for shutdown_get

        Requests a graceful termination of a job, executing the operating system poweroff mechanism if applicable.  # noqa: E501
        """
        pass

    def test_signal_get(self):
        """Test case for signal_get

        Send a signal to a running job (e.g. SIGTSTP/20).  # noqa: E501
        """
        pass

    def test_submit_post(self):
        """Test case for submit_post

        Submits a job for processing.  # noqa: E501
        """
        pass

    def test_terminate_get(self):
        """Test case for terminate_get

        Immediately terminates a running job. NB: This will terminate the job regardless of current status.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
