# coding: utf-8

"""
    Jarvice API

    The JARVICE API allows full control on running jobs as well as managing applications via PushToCompute™.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@nimbix.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import jarviceapi_client
from jarviceapi_client.models.job_obj_vault import JobObjVault  # noqa: E501
from jarviceapi_client.rest import ApiException

class TestJobObjVault(unittest.TestCase):
    """JobObjVault unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test JobObjVault
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobObjVault`
        """
        model = jarviceapi_client.models.job_obj_vault.JobObjVault()  # noqa: E501
        if include_optional :
            return JobObjVault(
                auth = '', 
                domain = '', 
                force = True, 
                var_global = jarviceapi_client.models.model_dict.ModelDict(), 
                name = '', 
                ro = True
            )
        else :
            return JobObjVault(
        )
        """

    def testJobObjVault(self):
        """Test JobObjVault"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
