# coding: utf-8

"""
    Jarvice API

    The JARVICE API allows full control on running jobs as well as managing applications via PushToCompute™.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@nimbix.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import jarviceapi_client
from jarviceapi_client.api.status_and_information_api import StatusAndInformationApi  # noqa: E501
from jarviceapi_client.rest import ApiException


class TestStatusAndInformationApi(unittest.TestCase):
    """StatusAndInformationApi unit test stubs"""

    def setUp(self):
        self.api = jarviceapi_client.api.status_and_information_api.StatusAndInformationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_appdef_get(self):
        """Test case for appdef_get

        Returns the Application Definition (AppDef) for a given application.  # noqa: E501
        """
        pass

    def test_apps_get(self):
        """Test case for apps_get

        Returns the Application Definition (AppDef) for a given application.  # noqa: E501
        """
        pass

    def test_billing_get(self):
        """Test case for billing_get

        (JXE/System Admins only) Returns billing report for JARVICE users  # noqa: E501
        """
        pass

    def test_connect_get(self):
        """Test case for connect_get

        Requests the network address and user nimbix password (if set), for an interactive job.  # noqa: E501
        """
        pass

    def test_events_get(self):
        """Test case for events_get

        (JXE/System Admins only) Retrieves event logs for a running job that are related to the cluster infrastructure  # noqa: E501
        """
        pass

    def test_info_get(self):
        """Test case for info_get

        Get info from job  # noqa: E501
        """
        pass

    def test_jobs_get(self):
        """Test case for jobs_get

        Returns job information and status for all queued and running jobs.  # noqa: E501
        """
        pass

    def test_license_get(self):
        """Test case for license_get

        (JXE/System Admins only) Retrieves Jarvice license  # noqa: E501
        """
        pass

    def test_live_get(self):
        """Test case for live_get

        Get info is API is alive  # noqa: E501
        """
        pass

    def test_machines_get(self):
        """Test case for machines_get

        Returns information about available machine type(s).  # noqa: E501
        """
        pass

    def test_metrics_get(self):
        """Test case for metrics_get

        Returns the last known CPU and memory utilization metrics for a given job.  # noqa: E501
        """
        pass

    def test_output_get(self):
        """Test case for output_get

        Returns a tail (or optionally all) of the output of a completed job.  # noqa: E501
        """
        pass

    def test_projects_get(self):
        """Test case for projects_get

        (JXE/System Admins only) Returns all JARVICE projects and members  # noqa: E501
        """
        pass

    def test_queues_get(self):
        """Test case for queues_get

        (JXE only) Returns information about available queue(s).  # noqa: E501
        """
        pass

    def test_ready_get(self):
        """Test case for ready_get

        Get info if DAL is ready  # noqa: E501
        """
        pass

    def test_screenshot_get(self):
        """Test case for screenshot_get

        Returns a screenshot for a running job (if it is graphical).  # noqa: E501
        """
        pass

    def test_status_get(self):
        """Test case for status_get

        Queries status for a previously submitted job.  # noqa: E501
        """
        pass

    def test_tail_get(self):
        """Test case for tail_get

        Returns a tail (or optionally all) of the output of a completed job.  # noqa: E501
        """
        pass

    def test_teamjobs_get(self):
        """Test case for teamjobs_get

        Returns job information and status for all queued and running jobs for an entire team.  # noqa: E501
        """
        pass

    def test_teamusers_get(self):
        """Test case for teamusers_get

        (Team Admins only) Returns a list of JARVICE users who are members of the callers team  # noqa: E501
        """
        pass

    def test_vault_get(self):
        """Test case for vault_get

        List files in a vault.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
