# coding: utf-8

"""
    Jarvice API

    The JARVICE API allows full control on running jobs as well as managing applications via PushToCompute™.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@nimbix.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictInt, StrictStr

class AppDefIdent(BaseModel):
    """
    AppDefIdent
    """
    gid: Optional[StrictInt] = None
    group: Optional[StrictStr] = None
    uid: Optional[StrictInt] = None
    username: Optional[StrictStr] = None
    __properties = ["gid", "group", "uid", "username"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AppDefIdent:
        """Create an instance of AppDefIdent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AppDefIdent:
        """Create an instance of AppDefIdent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AppDefIdent.parse_obj(obj)

        _obj = AppDefIdent.parse_obj({
            "gid": obj.get("gid"),
            "group": obj.get("group"),
            "uid": obj.get("uid"),
            "username": obj.get("username")
        })
        return _obj

