# coding: utf-8

"""
    Jarvice API

    The JARVICE API allows full control on running jobs as well as managing applications via PushToCompute™.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@nimbix.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictInt, StrictStr

class JobUpload(BaseModel):
    """
    JobUpload
    """
    data: Optional[StrictStr] = None
    size: Optional[StrictInt] = None
    target: Optional[StrictStr] = None
    __properties = ["data", "size", "target"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> JobUpload:
        """Create an instance of JobUpload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> JobUpload:
        """Create an instance of JobUpload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return JobUpload.parse_obj(obj)

        _obj = JobUpload.parse_obj({
            "data": obj.get("data"),
            "size": obj.get("size"),
            "target": obj.get("target")
        })
        return _obj

