# coding: utf-8

"""
    Jarvice API

    The JARVICE API allows full control on running jobs as well as managing applications via PushToCompute™.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@nimbix.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr

class Application(BaseModel):
    """
    Application
    """
    command: Optional[StrictStr] = None
    geometry: Optional[StrictStr] = None
    ipaddr: Optional[StrictStr] = None
    nosubmit: Optional[StrictBool] = Field(None, description="If this is set, then the API server just returns the jobobj rather than send it to the scheduler. Development mode python API does the same This only applies if JARVICE_API_LOG_ENABLE environment var is set")
    parameters: Optional[Dict[str, Any]] = None
    walltime: Optional[StrictStr] = None
    __properties = ["command", "geometry", "ipaddr", "nosubmit", "parameters", "walltime"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Application:
        """Create an instance of Application from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Application:
        """Create an instance of Application from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Application.parse_obj(obj)

        _obj = Application.parse_obj({
            "command": obj.get("command"),
            "geometry": obj.get("geometry"),
            "ipaddr": obj.get("ipaddr"),
            "nosubmit": obj.get("nosubmit"),
            "parameters": obj.get("parameters"),
            "walltime": obj.get("walltime")
        })
        return _obj

