# coding: utf-8

"""
    Jarvice API

    The JARVICE API allows full control on running jobs as well as managing applications via PushToCompute™.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@nimbix.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, StrictInt, conlist

class RTMetricsItemized(BaseModel):
    """
    RTMetricsItemized
    """
    cpu_used: Optional[conlist(StrictInt)] = None
    memory_total: Optional[conlist(StrictInt)] = None
    memory_used: Optional[conlist(StrictInt)] = None
    __properties = ["cpu_used", "memory_total", "memory_used"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RTMetricsItemized:
        """Create an instance of RTMetricsItemized from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RTMetricsItemized:
        """Create an instance of RTMetricsItemized from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RTMetricsItemized.parse_obj(obj)

        _obj = RTMetricsItemized.parse_obj({
            "cpu_used": obj.get("cpu_used"),
            "memory_total": obj.get("memory_total"),
            "memory_used": obj.get("memory_used")
        })
        return _obj

